import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{ShoppingCart,Search,Store,User,Package,ShieldCheck,Truck,Heart,BarChart3,Menu,X,Plus,Minus}from'lucide-react';
import'./styles.css';

const products=[
{id:1,name:'أرز مصري فاخر 5 كجم',cat:'أغذية',image:'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=900&q=80',stock:500,tiers:[{label:'قطاعي',min:1,max:9,price:220},{label:'جملة',min:10,max:49,price:195},{label:'جملة الجملة',min:50,max:500,price:178}]},
{id:2,name:'زيت عباد الشمس 1 لتر',cat:'زيوت',image:'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80',stock:800,tiers:[{label:'قطاعي',min:1,max:11,price:95},{label:'جملة',min:12,max:59,price:84},{label:'جملة الجملة',min:60,max:800,price:76}]},
{id:3,name:'سكر أبيض 1 كجم',cat:'أغذية',image:'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&w=900&q=80',stock:1000,tiers:[{label:'قطاعي',min:1,max:19,price:42},{label:'جملة',min:20,max:99,price:37},{label:'جملة الجملة',min:100,max:1000,price:33}]},
{id:4,name:'منظف أرضيات مركز 4 لتر',cat:'منظفات',image:'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=900&q=80',stock:300,tiers:[{label:'قطاعي',min:1,max:5,price:180},{label:'جملة',min:6,max:29,price:155},{label:'جملة الجملة',min:30,max:300,price:139}]}
];
function tierFor(p,q){return p.tiers.find(t=>q>=t.min&&q<=t.max)||p.tiers[p.tiers.length-1]}
function App(){const[query,setQuery]=useState('');const[cart,setCart]=useState({});const[open,setOpen]=useState(false);const filtered=useMemo(()=>products.filter(p=>p.name.includes(query)||p.cat.includes(query)),[query]);const add=(p,d)=>setCart(c=>({...c,[p.id]:Math.max(0,Math.min(p.stock,(c[p.id]||0)+d))}));const total=Object.entries(cart).reduce((s,[id,q])=>{const p=products.find(x=>x.id==id);return s+(p?tierFor(p,q).price*q:0)},0);return <>
<header><div className="brand">Tager<span>تاجر</span></div><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'show':''}><a>الرئيسية</a><a>المنتجات</a><a>الفئات</a><a>انضم كمورد</a><a>تواصل معنا</a></nav><div className="head-actions"><button><User size={18}/> دخول</button><button className="cart"><ShoppingCart size={18}/> {Object.values(cart).reduce((a,b)=>a+b,0)}</button></div></header>
<section className="hero"><div><span className="badge">منصة تجارة لكل الكميات</span><h1>اشتري قطاعي، جملة، أو جملة الجملة من مكان واحد</h1><p>سعر المنتج يتغير تلقائيًا حسب الكمية، مع حدود دنيا وعليا واضحة لكل مستوى بيع.</p><div className="hero-buttons"><button className="primary">ابدأ التسوق</button><button className="secondary">سجل كمورد</button></div></div><div className="hero-card"><Store size={56}/><h3>متجر واحد، ثلاث طرق بيع</h3><p>قطاعي بلا تعقيدات — جملة للتجار — جملة الجملة للموزعين.</p></div></section>
<section className="features">{[[Package,'أسعار متدرجة'],[ShieldCheck,'موردون موثوقون'],[Truck,'شحن ومتابعة'],[BarChart3,'لوحات تحكم ذكية']].map(([I,t])=><div><I/><b>{t}</b></div>)}</section>
<section className="products"><div className="section-head"><div><small>منتجات مختارة</small><h2>اكتشف أفضل العروض</h2></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن منتج أو قسم"/></div></div><div className="grid">{filtered.map(p=>{const q=cart[p.id]||1;const t=tierFor(p,q);return <article className="card" key={p.id}><div className="image"><img src={p.image}/><button><Heart size={18}/></button><span>{p.cat}</span></div><div className="content"><h3>{p.name}</h3><div className="tier">{p.tiers.map(x=><span className={t.label===x.label?'active':''}>{x.label}<b>{x.price} ج.م</b><small>{x.min}–{x.max}</small></span>)}</div><div className="buy"><div className="qty"><button onClick={()=>add(p,-1)}><Minus/></button><strong>{cart[p.id]||1}</strong><button onClick={()=>add(p,1)}><Plus/></button></div><div><small>السعر الحالي</small><b>{t.price} ج.م</b></div></div><button className="add" onClick={()=>setCart(c=>({...c,[p.id]:c[p.id]||1}))}><ShoppingCart size={18}/> أضف للسلة</button></div></article>})}</div></section>
<section className="dashboard"><div><small>للموردين</small><h2>تحكم كامل في الأسعار والكميات</h2><p>أضف سعر القطاعي والجملة وجملة الجملة، وحدد الحد الأدنى والأقصى والمخزون ومناطق الشحن.</p><button className="primary">افتح لوحة المورد</button></div><div className="stats"><div><b>1,248</b><span>طلب تجريبي</span></div><div><b>320</b><span>موردًا</span></div><div><b>98%</b><span>رضا العملاء</span></div><div><b>24/7</b><span>متابعة الطلبات</span></div></div></section>
<footer><div className="brand">Tager<span>تاجر</span></div><p>منصة تجارة إلكترونية للقطاعي والجملة وجملة الجملة.</p><small>نسخة تجريبية قابلة للتطوير والربط بقاعدة بيانات ودفع إلكتروني.</small></footer>
<div className="cartbar"><span>إجمالي السلة</span><b>{total.toLocaleString()} ج.م</b></div>
</>}
createRoot(document.getElementById('root')).render(<App/>);
